tutorial/accounts/urls.py
from django.conf.urls import url

from django.contrib.auth.views import (
    login,logout,password_reset_complete,password_reset_done,
    password_reset_confirm,password_reset
)
from .views import register,profile,profile_edit,change_password
#add urls for all apps
urlpatterns = [

    url(r'^login/$', login,{'template_name':"accounts/login.html"},name='login'),
    url(r'^logout/$', logout,{'template_name':"accounts/logout.html"},name='logout'),
    url(r'^register/$', register,name='register'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^profile/(?P<pk>\d+)/$', profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', profile_edit, name='profile_edit'),
    url(r'^change-password/$', change_password, name='change_password'),
    url(r'^reset-password/$',password_reset,{'template_name':
        "accounts/reset_password.html","post_reset_redirect":"accounts:password_reset_done",
                                             'email_template_name':"accounts/reset_password_email.html"},
        name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done,{'template_name':'accounts/reset_password_done.html'}
        ,name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name':"accounts/reset_password_confirm.html",
         'post_reset_redirect':'accounts:password_reset_complete'},name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,{'template_name':
        "accounts/reset_password_complete.html",} ,name='password_reset_complete')
]

tutorial/home/urls.py
from django.conf.urls import url
from home.views import HomeView,change_friend,message_to_friend
urlpatterns = [
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',change_friend, name='change_friend'),
    url(r'^message/$', message_to_friend, name='message_to_friend')
    ]

tutorial/tutorial/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import login_redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', login_redirect),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls',namespace='accounts')),
    url(r'^home/', include('home.urls',namespace='home')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='gwalior')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)
    #objects = models.Manager()
    gwalior = UserProfileManager()

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

tutorial/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from django import forms
#add contact details and address for user
class RegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)

    class Meta:
        model=User
        fields=(
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user=super(RegistrationForm,self).save(commit=False)
        user.first_name=self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']

        if commit:
            user.save()

        return user
#add contact details for user
class EditProfileForm(UserChangeForm):

    class Meta:
        model=User
        fields=(
            'email',
            'first_name',
            'last_name',
            'password'
        )

tutorial/accounts/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from django.urls import reverse
from .forms import RegistrationForm,EditProfileForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
# Create your views here.

def register(request):

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('home:home'))
        else:
            print(form.errors)
    else:
        form = RegistrationForm()

    args={'form':form}
    return render(request, 'accounts/reg_form.html', args)

def profile(request,pk=None):
    if pk:
        user=User.objects.get(pk=pk)
    else:
        user=request.user
    args={'user':user}
    return render(request,'accounts/profile.html',args)

def profile_edit(request):
    if request.method == 'POST':
        form= EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:profile'))
        else:
            print(form.errors)
    else:
        form=EditProfileForm(instance=request.user)

    args={'form':form}
    return render(request,'accounts/edit_profile.html',args)

def change_password(request):
    if request.method == 'POST':
        form= PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)     #for user to remain logged in
            return redirect(reverse('accounts:profile'))
        else:
            print(form.errors)
    else:
        form=PasswordChangeForm(user=request.user)

    args={'form':form}
    return render(request,'accounts/change-password.html',args)

tutorial/accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

   {% load static %}
   <!--ink href="{% static 'accounts/navbar.css' %}" rel="stylesheet"-->
  <meta name="viewport" content="width=devide-width, initial-scale=1.0">
  {% block head %}
  <title>base</title>
  {% endblock %}
</head>
<body>
    <br>
    <!--div class="container"-->

      <!-- Static navbar -->
      <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Network</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">

          {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
                <li><a href="{% url 'home:home' %}">Home</a></li>
                <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                <li><a href="{% url 'accounts:profile_edit' %}">Edit Profile</a></li>
                <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                <li><a href="">Messages</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'accounts:login' %}">Login</a></li>
              <li><a href="{% url 'accounts:register' %}">Register</a></li>
            </ul>
            {% endif %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>


    {% block body %}
    {% endblock %}
    </div>
</body>
</html>