tutorial/accounts/urls.py
from django.conf.urls import url

from django.contrib.auth.views import (
    login,logout,password_reset_complete,password_reset_done,
    password_reset_confirm,password_reset
)
from .views import register,profile,profile_edit,change_password
#add urls for all apps
urlpatterns = [

    url(r'^login/$', login,{'template_name':"accounts/login.html"},name='login'),
    url(r'^logout/$', logout,{'template_name':"accounts/logout.html"},name='logout'),
    url(r'^register/$', register,name='register'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^profile/(?P<pk>\d+)/$', profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', profile_edit, name='profile_edit'),
    url(r'^change-password/$', change_password, name='change_password'),
    url(r'^reset-password/$',password_reset,{'template_name':
        "accounts/reset_password.html","post_reset_redirect":"accounts:password_reset_done",
                                             'email_template_name':"accounts/reset_password_email.html"},
        name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done,{'template_name':'accounts/reset_password_done.html'}
        ,name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name':"accounts/reset_password_confirm.html",
         'post_reset_redirect':'accounts:password_reset_complete'},name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,{'template_name':
        "accounts/reset_password_complete.html",} ,name='password_reset_complete')
]

tutorial/home/urls.py
from django.conf.urls import url
from home.views import HomeView,change_friend,message_to_friend
urlpatterns = [
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',change_friend, name='change_friend'),
    url(r'^message/$', message_to_friend, name='message_to_friend')
    ]

tutorial/tutorial/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import login_redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', login_redirect),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls',namespace='accounts')),
    url(r'^home/', include('home.urls',namespace='home')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='gwalior')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)
    #objects = models.Manager()
    gwalior = UserProfileManager()

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

tutorial/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from django import forms
#add contact details and address for user
class RegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)

    class Meta:
        model=User
        fields=(
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user=super(RegistrationForm,self).save(commit=False)
        user.first_name=self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']

        if commit:
            user.save()

        return user
#add contact details for user
class EditProfileForm(UserChangeForm):

    class Meta:
        model=User
        fields=(
            'email',
            'first_name',
            'last_name',
            'password'
        )

tutorial/accounts/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from django.urls import reverse
from .forms import RegistrationForm,EditProfileForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
# Create your views here.

def register(request):

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('home:home'))
        else:
            print(form.errors)
    else:
        form = RegistrationForm()

    args={'form':form}
    return render(request, 'accounts/reg_form.html', args)

def profile(request,pk=None):
    if pk:
        user=User.objects.get(pk=pk)
    else:
        user=request.user
    args={'user':user}
    return render(request,'accounts/profile.html',args)

def profile_edit(request):
    if request.method == 'POST':
        form= EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:profile'))
        else:
            print(form.errors)
    else:
        form=EditProfileForm(instance=request.user)

    args={'form':form}
    return render(request,'accounts/edit_profile.html',args)

def change_password(request):
    if request.method == 'POST':
        form= PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)     #for user to remain logged in
            return redirect(reverse('accounts:profile'))
        else:
            print(form.errors)
    else:
        form=PasswordChangeForm(user=request.user)

    args={'form':form}
    return render(request,'accounts/change-password.html',args)

tutorial/accounts/templates/accounts/change-password.html
{%  extends 'base.html' %}

{% block body %}
<h2>Profile</h2>
<p>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">submit</button>
</form>
</p>
{% endblock %}

tutorial/accounts/templates/accounts/edit_profile.html
{%  extends 'base.html' %}

{% block body %}
<h2>Profile</h2>
<p>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">submit</button>
</form>
</p>
{% endblock %}

tutorial/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block head %}
<title>login</title>
{% endblock %}

{% block body %}

<div class="container">
<h1>Welcome</h1>
<p>login here</p>

<form method="post">
{% csrf_token %}
{{form.as_p}}

<button type="submit" >Login</button><br>
Forgot account? <a href="{% url 'accounts:reset_password' %}">Click Here</a>
</form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block head %}
<title>logged out</title>
{% endblock %}

{% block body %}
successfully logged out
{% endblock %}

tutorial/accounts/templates/accounts/profile.html
{%  extends 'base.html' %}

{% block body %}
<h2>Profile</h2>
<p>
{% if user.userprofile.image %}
<img src="{{user.userprofile.image.url}}" width="240px"><br>
{% endif %}
Username:{{user.username}}<br>
First Name:{{ user.first_name }}<br>
Last Name:{{ user.last_name }}<br>
Email:{{ user.email }}<br>
Description:{{ user.userprofile.description }}<br>
Website:{{ user.userprofile.website }}<br>
Phone:{{ user.userprofile.phone }}<br>
City:{{ user.userprofile.city }}<br>

</p>
{% endblock %}

tutorial/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<h1>Register</h1>
<form method="POST">

{% csrf_token %}
{{ form.as_p }}
<button type="submit" >Submit</button>
</form>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password.html
{%  extends 'base.html' %}

{% block body %}
<h2>Reset password</h2>
<p>
Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">submit</button>
</form>
</p>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password_complete.html
{%  extends 'base.html' %}

{% block body %}
<h2>Reset password complete</h2>
<p>
<a href="{% url 'accounts:login' %}">Login</a>
</p>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password_confirm.html
{%  extends 'base.html' %}

{% block body %}
<h2>Enter New Password</h2>
<p>
Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Reset</button>
</form>
</p>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password_done.html
{%  extends 'base.html' %}

{% block body %}
<h2>Password reset sent</h2>
<p>
We've emailed you instructions for setting your password, if an account exists
with the email you entered. You should receive them shortly.
<br>
If you don't receive an email, please make sure you've entered the address you registered with,
 and check your spam folder.
</p>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

	{% trans "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

	{% trans "Thanks for using our site!" %}

	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

	{% endautoescape %}