tutorial/accounts/urls.py
from django.conf.urls import url

from django.contrib.auth.views import (
    login,logout,password_reset_complete,password_reset_done,
    password_reset_confirm,password_reset
)
from .views import register,profile,profile_edit,change_password
#add urls for all apps
urlpatterns = [

    url(r'^login/$', login,{'template_name':"accounts/login.html"},name='login'),
    url(r'^logout/$', logout,{'template_name':"accounts/logout.html"},name='logout'),
    url(r'^register/$', register,name='register'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^profile/(?P<pk>\d+)/$', profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', profile_edit, name='profile_edit'),
    url(r'^change-password/$', change_password, name='change_password'),
    url(r'^reset-password/$',password_reset,{'template_name':
        "accounts/reset_password.html","post_reset_redirect":"accounts:password_reset_done",
                                             'email_template_name':"accounts/reset_password_email.html"},
        name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done,{'template_name':'accounts/reset_password_done.html'}
        ,name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name':"accounts/reset_password_confirm.html",
         'post_reset_redirect':'accounts:password_reset_complete'},name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,{'template_name':
        "accounts/reset_password_complete.html",} ,name='password_reset_complete')
]

tutorial/home/urls.py
from django.conf.urls import url
from home.views import HomeView,change_friend,message_to_friend
urlpatterns = [
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',change_friend, name='change_friend'),
    url(r'^message/$', message_to_friend, name='message_to_friend')
    ]

tutorial/tutorial/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import login_redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', login_redirect),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls',namespace='accounts')),
    url(r'^home/', include('home.urls',namespace='home')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
#add mutual friend model here 
#add profile model for user

class Post(models.Model):
    post=models.CharField(max_length=100)
    user=models.ForeignKey(User)
    created=models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'written by %s' % (self.user)

class Friend(models.Model):
    users=models.ManyToManyField(User)
    current_user=models.ForeignKey(User,related_name='owner',null=True)

    @classmethod
    def make_friend(cls,current_user,new_friend):
        friend, created=cls.objects.get_or_create(current_user=current_user)
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(current_user=current_user)
        friend.users.remove(new_friend)

#add date and time 	field for messages model
class Messages(models.Model):
    content=models.CharField(max_length=500)

tutorial/home/forms.py
from django import forms
from home.models import Post

class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a post...'
        }
    ))

    class Meta:
        model = Post
        fields = ('post',) # "," is used to store tuple

tutorial/home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render,HttpResponseRedirect,reverse,redirect
from home.forms import HomeForm
from home.models import Post,Friend
from django.contrib.auth.models import User

class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request, *args, **kwargs):
        form=HomeForm()
        posts=Post.objects.all().order_by('-created')
        users=User.objects.exclude(pk=request.user.pk)
        try:
            friend=Friend.objects.get(current_user=request.user)
        except Friend.DoesNotExist:
            friend=None
        if friend:
            friends = friend.users.all()
        else:
            friends = None

        args={'form':form,'posts':posts,'users':users,'friends':friends}
        return render(request,self.template_name,args)

    def post(self,request):
        form=HomeForm(request.POST)
        text=''
        if form.is_valid():
            post_object=form.save(commit=False)
            post_object.user = request.user
            form.save()
            text=form.cleaned_data['post']
            form=HomeForm()
            return HttpResponseRedirect(reverse('home:home'))

        args={'form':form,'text':text}
        return render(request,self.template_name,args)

def change_friend(request,operation,pk):
    new_friend=User.objects.get(pk=pk)
    #print(operation,pk)
    if operation == 'add':
        Friend.make_friend(request.user,new_friend)
    elif operation == 'remove':
        Friend.lose_friend(request.user,new_friend)
    return redirect('home:home')


def message_to_friend(request):
    print(request)
    return redirect('home:home')

tutorial/home/templates/home/home.html
{% extends 'base.html' %}

{% block body %}
<div class="col-md-8">
    <h2>Home</h2>
    <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Submit</button>
    <p>
    {% for post in posts %}
    {% if post.user in friends or post.user == user  %}
    <h1>{{post.post}}</h1>
    <p>Posted by {{post.user.get_full_name}} on {{post.created}}</p>
    {% endif %}
    {% endfor %}
    </p>
    </form>

</div>
<div class="col-md-4">
    <h2>Other people</h2>
    {% for user in users %}
    <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}" ><h3>{{user.username}}</h3></a>

    {% if not user in friends %}
    <a href="{% url 'home:change_friend' pk=user.pk operation='add' %}">
    <button class="btn btn-success">Add friend</button>
    </a>
    {% endif %}

    {% endfor %}
    <h2>Friends</h2>
    {% if friends %}
    {% for friend in friends %}
    <a href="{% url 'accounts:view_profile_with_pk' pk=friend.pk %}" ><h3>{{friend.username}}</h3></a>

    <a href="{% url 'home:change_friend' pk=friend.pk operation='remove' %}">
    <button class="btn btn-default">Remove friend</button>
    </a>

    <button class="btn btn-info" onclick="addInput() ">Message</button>
    {% endfor %}
    {% endif %}
</div>

<span id="responce"></span>
<script>
var countBox =1;
var boxName = 0;
function addInput()
{
    var csrftoken = '{{ csrf_token }}';
     var boxName="textBox"+countBox;
document.getElementById('responce').innerHTML+='' + '<br/>' + '<form method="post" action="/home/message/">' +
 csrftoken + '<input type="text" id="'+boxName+'" value="'+boxName+'" "  /><br/> ' +
 '<input type="submit" value="Submit"></form> <br/>';
     countBox += 1;
}
</script>

{% endblock %}